version: "2.2"
services:
  frontend:
    image: bloodisblue/my-blog:1.3.0
    ports:
      - "4200:80"
  backend:
    image: bloodisblue/blog-backend:1.2.0
    ports:
      - "8888:8888"
  kelly-criterion:
    image: bloodisblue/kelly-criterion-client:1.1.0
    ports:
      - "8001:80"
